[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1197374c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bdbe2775234f5940c1a0570eb6e74e10/timeouts
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1197372b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bdbe2775234f5940c1a0570eb6e74e10/timeouts
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x119737190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/bdbe2775234f5940c1a0570eb6e74e10/timeouts